# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Mateusz Okulanis
"""The parts that read what the installer wrote."""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from shuttle_delegate.config import ConfigError, load_endpoints, read_env

COMPLETE = """\
# Generated by shuttle install.sh; local edits are overwritten.
SHUTTLE_NETWORK=shuttle
SHUTTLE_LONG_URL=http://shuttle-long:8080
SHUTTLE_LONG_IP=10.89.7.10
SHUTTLE_LONG_DIRECT_PORT=8081
SHUTTLE_FAST_URL=http://shuttle-fast:8080
SHUTTLE_FAST_IP=10.89.7.11
SHUTTLE_FAST_DIRECT_PORT=8082
"""

NO_PORTS = """\
SHUTTLE_NETWORK=shuttle
SHUTTLE_LONG_URL=http://shuttle-long:8080
SHUTTLE_FAST_URL=http://shuttle-fast:8080
"""


class EnvFileTest(unittest.TestCase):
    def setUp(self) -> None:
        self.dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.dir.cleanup)

    def write(self, text: str) -> Path:
        path = Path(self.dir.name) / "stack.env"
        path.write_text(text)
        return path

    def test_comments_and_blank_lines_are_skipped(self) -> None:
        env = read_env(self.write(COMPLETE))
        self.assertNotIn("#", "".join(env))
        self.assertEqual(env["SHUTTLE_LONG_DIRECT_PORT"], "8081")

    def test_a_missing_file_names_the_phase_that_writes_it(self) -> None:
        path = Path(self.dir.name) / "absent.env"
        with self.assertRaises(ConfigError) as caught:
            read_env(path)
        self.assertIn("quadlets", str(caught.exception))

    def test_endpoints_use_the_published_host_ports(self) -> None:
        endpoints = load_endpoints(self.write(COMPLETE))
        self.assertEqual(endpoints["long"].url, "http://127.0.0.1:8081")
        self.assertEqual(endpoints["fast"].url, "http://127.0.0.1:8082")

    def test_an_unreachable_install_is_reported_not_guessed(self) -> None:
        with self.assertRaises(ConfigError) as caught:
            load_endpoints(self.write(NO_PORTS))
        self.assertIn("--no-expose-direct", str(caught.exception))


if __name__ == "__main__":
    unittest.main()
